from __future__ import annotations

import os
import shlex
from pathlib import Path

from .config import RuntimeConfig


def shell_quote(value: str | Path) -> str:
    return shlex.quote(str(value))


def generate_runtime_outputs(config: RuntimeConfig, cli_path: Path = Path("/usr/bin/alfilogctl")) -> None:
    generated_dir = config.main.state_base / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)

    nrpe_lines = ["# Generated by alfilogd. Run install-nrpe-addon.sh as root to install."]
    for facility in sorted(config.facilities.values(), key=lambda item: item.output):
        if not facility.enabled:
            continue
        output_dir = config.main.output_base / facility.output
        output_dir.mkdir(parents=True, exist_ok=True)
        os.chmod(output_dir, 0o755)
        status_file = output_dir / "status.json"
        get_script = output_dir / "get.sh"
        max_age = max(60, int(config.main.status_write_interval * 5))
        get_script.write_text(
            "#!/usr/bin/env bash\n"
            "set -u\n"
            f"exec {shell_quote(cli_path)} status --status-file {shell_quote(status_file)} "
            f"--max-age {max_age} --nagios\n",
            encoding="utf-8",
        )
        os.chmod(get_script, 0o755)
        command_name = f"check_alfilogd_{facility.output}".replace("-", "_").replace(".", "_")
        nrpe_lines.append(f"command[{command_name}]={get_script}")

    nrpe_generated = generated_dir / config.nrpe.generated_name
    nrpe_generated.write_text("\n".join(nrpe_lines) + "\n", encoding="utf-8")
    os.chmod(nrpe_generated, 0o644)

    installer = generated_dir / "install-nrpe-addon.sh"
    installer.write_text(
        "#!/usr/bin/env bash\n"
        "set -Eeuo pipefail\n"
        "if [[ ${EUID:-$(id -u)} -ne 0 ]]; then echo 'Run as root.' >&2; exit 1; fi\n"
        f"SOURCE={shell_quote(nrpe_generated)}\n"
        f"TARGET_DIR={shell_quote(config.nrpe.include_dir)}\n"
        f"TARGET=\"$TARGET_DIR/{config.nrpe.generated_name}\"\n"
        "install -d -o root -g root -m 0755 \"$TARGET_DIR\"\n"
        "install -o root -g root -m 0644 \"$SOURCE\" \"$TARGET\"\n"
        f"VALIDATE={shell_quote(config.nrpe.validate_command)}\n"
        f"RELOAD={shell_quote(config.nrpe.reload_command)}\n"
        "if [[ -n \"$VALIDATE\" ]]; then bash -lc \"$VALIDATE\"; fi\n"
        "if [[ -n \"$RELOAD\" ]]; then bash -lc \"$RELOAD\"; fi\n"
        "echo \"Installed $TARGET\"\n",
        encoding="utf-8",
    )
    os.chmod(installer, 0o750)
